# Generated by Django 5.2.8 on 2025-12-14 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postcard',
            name='has_animation',
        ),
    ]
