# Generated by Django 5.2.8 on 2025-12-02 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postcard',
            name='dos_image',
        ),
        migrations.RemoveField(
            model_name='postcard',
            name='grande_image',
        ),
        migrations.RemoveField(
            model_name='postcard',
            name='vignette_image',
        ),
        migrations.RemoveField(
            model_name='postcard',
            name='zoom_image',
        ),
        migrations.AddField(
            model_name='postcard',
            name='dos_url',
            field=models.URLField(blank=True, max_length=500, verbose_name='URL Dos'),
        ),
        migrations.AddField(
            model_name='postcard',
            name='grande_url',
            field=models.URLField(blank=True, max_length=500, verbose_name='URL Grande'),
        ),
        migrations.AddField(
            model_name='postcard',
            name='vignette_url',
            field=models.URLField(blank=True, max_length=500, verbose_name='URL Vignette'),
        ),
        migrations.AddField(
            model_name='postcard',
            name='zoom_url',
            field=models.URLField(blank=True, max_length=500, verbose_name='URL Zoom'),
        ),
        migrations.AlterField(
            model_name='postcard',
            name='keywords',
            field=models.TextField(blank=True, help_text='Séparés par des virgules', verbose_name='Mots-clés'),
        ),
    ]
