# Generated by Django 5.2.8 on 2025-12-02 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_postcard_dos_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='postcard',
            name='animated_url',
            field=models.URLField(blank=True, max_length=500, verbose_name='URL Animation'),
        ),
    ]
