# Generated by Django 5.2.8 on 2025-12-19 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_dailyanalytics_iplocation_customuser_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentpostcard',
            name='is_animated',
            field=models.BooleanField(default=False, verbose_name='Carte animée'),
        ),
        migrations.AddField(
            model_name='sentpostcard',
            name='stamp_type',
            field=models.CharField(choices=[('5c', '5 centimes - 44 caractères'), ('10c', '10 centimes - 55 caractères')], default='10c', max_length=10, verbose_name='Type de timbre'),
        ),
        migrations.AlterField(
            model_name='sentpostcard',
            name='message',
            field=models.TextField(max_length=55, verbose_name='Message'),
        ),
    ]
