# Generated by Django 5.2.8 on 2025-12-19 21:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_sentpostcard_is_animated_sentpostcard_stamp_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='allow_messages',
            field=models.BooleanField(default=True, verbose_name='Autoriser les messages'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='covers/', verbose_name='Image de couverture'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='favorite_postcard',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='favorited_by', to='core.postcard', verbose_name='Carte préférée'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='profile_cover',
            field=models.ImageField(blank=True, null=True, upload_to='covers/', verbose_name='Image de couverture'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='show_activity',
            field=models.BooleanField(default=True, verbose_name="Afficher l'activité"),
        ),
        migrations.AddField(
            model_name='customuser',
            name='show_connections',
            field=models.BooleanField(default=True, verbose_name='Afficher les connexions'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='website',
            field=models.URLField(blank=True, verbose_name='Site web'),
        ),
        migrations.AddField(
            model_name='useractivity',
            name='related_postcard',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.postcard'),
        ),
        migrations.AddField(
            model_name='useractivity',
            name='related_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_activities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='useractivity',
            name='action',
            field=models.CharField(choices=[('login', 'Connexion'), ('logout', 'Déconnexion'), ('register', 'Inscription'), ('verify_email', 'Vérification email'), ('postcard_view', 'Vue carte postale'), ('postcard_zoom', 'Zoom carte postale'), ('postcard_like', 'Like carte postale'), ('postcard_unlike', 'Unlike carte postale'), ('animation_like', 'Like animation'), ('animation_suggest', 'Suggestion animation'), ('search', 'Recherche'), ('contact', 'Message de contact'), ('page_view', 'Vue de page'), ('postcard_sent', 'Carte envoyée'), ('postcard_received', 'Carte reçue'), ('profile_update', 'Mise à jour profil'), ('connection_add', 'Ajout connexion')], max_length=20),
        ),
        migrations.AlterField(
            model_name='visitorsession',
            name='os_version',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.CreateModel(
            name='UserConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_favorite', models.BooleanField(default=False, verbose_name='Favori')),
                ('notes', models.TextField(blank=True, max_length=200, verbose_name='Notes personnelles')),
                ('connected_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections_to', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections_from', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Connexion',
                'verbose_name_plural': 'Connexions',
                'unique_together': {('user', 'connected_to')},
            },
        ),
    ]
