# Generated by Django 5.2.8 on 2025-12-03 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_likes_suggestions_intro'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='postcardlike',
            name='unique_user_like',
        ),
        migrations.RemoveConstraint(
            model_name='postcardlike',
            name='unique_session_like',
        ),
        migrations.AlterField(
            model_name='introseen',
            name='session_key',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='postcardlike',
            unique_together={('postcard', 'session_key', 'is_animated_like'), ('postcard', 'user', 'is_animated_like')},
        ),
    ]
