# Generated by Django 5.2.8 on 2025-12-19 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_customuser_allow_messages_customuser_cover_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='password_set',
            field=models.BooleanField(default=True, verbose_name='Mot de passe défini'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='verification_code',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='Code de vérification'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='verification_code_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
