# Generated by Django 5.2.8 on 2025-12-20 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_customuser_password_set_customuser_verification_code_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postcardlike',
            options={'ordering': ['-created_at'], 'verbose_name': 'Like', 'verbose_name_plural': 'Likes'},
        ),
        migrations.AddField(
            model_name='postcardlike',
            name='browser',
            field=models.CharField(blank=True, max_length=100, verbose_name='Navigateur'),
        ),
        migrations.AddField(
            model_name='postcardlike',
            name='city',
            field=models.CharField(blank=True, max_length=100, verbose_name='Ville'),
        ),
        migrations.AddField(
            model_name='postcardlike',
            name='country',
            field=models.CharField(blank=True, max_length=100, verbose_name='Pays'),
        ),
        migrations.AddField(
            model_name='postcardlike',
            name='device_type',
            field=models.CharField(blank=True, max_length=50, verbose_name="Type d'appareil"),
        ),
        migrations.AddField(
            model_name='postcardlike',
            name='user_agent',
            field=models.TextField(blank=True, verbose_name='User Agent'),
        ),
        migrations.CreateModel(
            name='HourlyAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('hour', models.IntegerField()),
                ('page_views', models.IntegerField(default=0)),
                ('unique_visitors', models.IntegerField(default=0)),
                ('searches', models.IntegerField(default=0)),
                ('likes', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Analytique horaire',
                'verbose_name_plural': 'Analytiques horaires',
                'ordering': ['-date', '-hour'],
                'unique_together': {('date', 'hour')},
            },
        ),
    ]
