# Generated by Django 5.2.8 on 2025-12-03 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_postcardvideo'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='postcardlike',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='postcard',
            name='animated_url',
            field=models.TextField(blank=True, max_length=2000, verbose_name='URL Animation(s) (legacy)'),
        ),
    ]
