# Generated by Django 5.2.8 on 2025-12-23 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_postcardlike_options_postcardlike_browser_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitorsession',
            name='actions_count',
            field=models.IntegerField(default=0, verbose_name="Nombre d'actions"),
        ),
        migrations.AddField(
            model_name='visitorsession',
            name='exit_page',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='visitorsession',
            name='is_returning',
            field=models.BooleanField(default=False, verbose_name='Visiteur récurrent'),
        ),
        migrations.AddField(
            model_name='visitorsession',
            name='likes_count',
            field=models.IntegerField(default=0, verbose_name='Nombre de likes'),
        ),
        migrations.AddField(
            model_name='visitorsession',
            name='searches_count',
            field=models.IntegerField(default=0, verbose_name='Nombre de recherches'),
        ),
        migrations.AddField(
            model_name='visitorsession',
            name='session_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visitorsession',
            name='session_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
