# Generated by Django 5.2.8 on 2025-12-10 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_sent_postcards'),
    ]

    operations = [
        migrations.AddField(
            model_name='postcardvideo',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='animated_cp/', verbose_name='Vidéo Animée'),
        ),
    ]
