# Generated by Django 5.2.8 on 2025-12-11 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_postcardvideo_video_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='postcard',
            name='local_dos',
            field=models.ImageField(blank=True, null=True, upload_to='Dos/', verbose_name='Dos Image'),
        ),
        migrations.AddField(
            model_name='postcard',
            name='local_grande',
            field=models.ImageField(blank=True, null=True, upload_to='Grande/', verbose_name='Grande Image'),
        ),
        migrations.AddField(
            model_name='postcard',
            name='local_vignette',
            field=models.ImageField(blank=True, null=True, upload_to='Vignette/', verbose_name='Vignette Image'),
        ),
        migrations.AddField(
            model_name='postcard',
            name='local_zoom',
            field=models.ImageField(blank=True, null=True, upload_to='Zoom/', verbose_name='Zoom Image'),
        ),
    ]
