# Generated by Django 5.2.8 on 2025-12-11 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_postcard_local_dos_postcard_local_grande_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postcard',
            name='local_dos',
        ),
        migrations.RemoveField(
            model_name='postcard',
            name='local_grande',
        ),
        migrations.RemoveField(
            model_name='postcard',
            name='local_vignette',
        ),
        migrations.RemoveField(
            model_name='postcard',
            name='local_zoom',
        ),
        migrations.AlterField(
            model_name='postcard',
            name='animated_url',
            field=models.TextField(blank=True, max_length=2000, verbose_name='URL Animation(s)'),
        ),
    ]
