# Generated by Django 5.2.8 on 2025-12-11 15:09

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_local_image_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcardvideo',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to=core.models.animated_video_path, verbose_name='Vidéo Animée'),
        ),
        migrations.AlterField(
            model_name='postcardvideo',
            name='video_url',
            field=models.URLField(blank=True, max_length=500, verbose_name='URL Vidéo (legacy)'),
        ),
    ]
